// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCommandLineCommands() {
  return window['go']['main']['App']['GetCommandLineCommands']();
}

export function GetOSName() {
  return window['go']['main']['App']['GetOSName']();
}

export function CloseLeftWatch() {
  window['go']['main']['App']['CloseLeftWatch']();
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function DirExists(arg1) {
  return window['go']['main']['App']['DirExists'](arg1);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function SetLeftDirWatch(arg1) {
  window['go']['main']['App']['SetLeftDirWatch'](arg1);
}

export function CopyEntries(arg1, arg2) {
  window['go']['main']['App']['CopyEntries'](arg1, arg2);
}

export function DeleteEntries(arg1) {
  window['go']['main']['App']['DeleteEntries'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RunCommandLine(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunCommandLine'](arg1, arg2, arg3, arg4);
}

export function CloseRightWatch() {
  window['go']['main']['App']['CloseRightWatch']();
}

export function SetClip(arg1) {
  window['go']['main']['App']['SetClip'](arg1);
}

export function SplitFile(arg1) {
  return window['go']['main']['App']['SplitFile'](arg1);
}

export function WriteFile(arg1, arg2) {
  window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function RenameEntry(arg1, arg2) {
  window['go']['main']['App']['RenameEntry'](arg1, arg2);
}

export function AppendPath(arg1, arg2) {
  return window['go']['main']['App']['AppendPath'](arg1, arg2);
}

export function MakeDir(arg1) {
  window['go']['main']['App']['MakeDir'](arg1);
}

export function MakeFile(arg1) {
  window['go']['main']['App']['MakeFile'](arg1);
}

export function SetRightDirWatch(arg1) {
  window['go']['main']['App']['SetRightDirWatch'](arg1);
}

export function AddWatcher(arg1, arg2, arg3) {
  window['go']['main']['App']['AddWatcher'](arg1, arg2, arg3);
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function Quit() {
  window['go']['main']['App']['Quit']();
}

export function RemoveWatcher(arg1, arg2) {
  window['go']['main']['App']['RemoveWatcher'](arg1, arg2);
}

export function GetClip() {
  return window['go']['main']['App']['GetClip']();
}

export function GetEnvironment() {
  return window['go']['main']['App']['GetEnvironment']();
}

export function GetError() {
  return window['go']['main']['App']['GetError']();
}

export function MoveEntries(arg1, arg2) {
  window['go']['main']['App']['MoveEntries'](arg1, arg2);
}
