// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SetLeftDirWatch(arg1:string):void;

export function AddWatcher(arg1:string,arg2:number,arg3:string):void;

export function CloseRightWatch():void;

export function RunCommandLine(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:string):Promise<string>;

export function SetRightDirWatch(arg1:string):void;

export function CloseLeftWatch():void;

export function GetError():Promise<string>;

export function DeleteEntries(arg1:string):void;

export function MoveEntries(arg1:string,arg2:string):void;

export function Quit():void;

export function ReadDir(arg1:string):Promise<Array<main.FileInfo>>;

export function GetClip():Promise<string>;

export function MakeDir(arg1:string):void;

export function DirExists(arg1:string):Promise<boolean>;

export function WriteFile(arg1:string,arg2:string):void;

export function FileExists(arg1:string):Promise<boolean>;

export function GetCommandLineCommands():Promise<Array<string>>;

export function SplitFile(arg1:string):Promise<main.FileParts>;

export function GetEnvironment():Promise<Array<string>>;

export function SetClip(arg1:string):void;

export function GetHomeDir():Promise<string>;

export function GetOSName():Promise<string>;

export function MakeFile(arg1:string):void;

export function ReadFile(arg1:string):Promise<string>;

export function RemoveWatcher(arg1:string,arg2:number):void;

export function RenameEntry(arg1:string,arg2:string):void;

export function AppendPath(arg1:string,arg2:string):Promise<string>;

export function CopyEntries(arg1:string,arg2:string):void;
